---
title: "Group_Project_EF"
output: html_document
date: '2022-08-04'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Install Packages

```{r, message=FALSE}
library(fpp)
library(tseries)
library(ggplot2)
library(forecast)
library(TSstudio)
library(MLmetrics)
library(vars)
library(dplyr)
library(TSA)
```

## Importing Data

Import raw data. Selecting data for all providers and airlines. Data is by month by provider, so need to aggregate by month.

```{r load}
data <- read.csv('C:/Users/ethan/OneDrive/Documents/UChicago/Time Series Analysis/Group_Project/BTS_Airline_Delay_Data.csv')
data[is.na(data)] <- 0
data$date <- as.Date(paste(data$year,'-',data$month,'-','01', sep = ''))
flights <- data %>% group_by(date) %>%
  summarise(flights = sum(arr_flights), delays = sum(arr_del15), carrier = sum(carrier_ct),
            weather = sum(weather_ct), nas = sum(nas_ct), security = sum(security_ct), 
            late_aircraft = sum(late_aircraft_ct), late_aircraft = sum(late_aircraft_ct),
            cancellation = sum(arr_cancelled), diversions = sum(arr_diverted))
flights = subset(flights, select = -c(date))
flights_ts <- ts(flights, start = c(2003,6), frequency = 12)
total_flights <- flights_ts[,1]
total_delays <- flights_ts[,2]
total_flights_pre_covid <- window(total_flights, end=2019.99)
total_delays_pre_covid <- window(total_delays, end=2019.99)
```

## EDA

Plot our main time series

```{r 1}
#all
tsdisplay(total_flights)
tsdisplay(total_delays)

#pre_covid
tsdisplay(total_flights_pre_covid)
tsdisplay(total_delays_pre_covid)
```

## KPSS Test

```{r 2}
#No Differencing
kpss.test(total_delays)
plot(total_delays)
#not stationary

#1st order difference
kpss.test(diff(total_delays))
plot(diff(total_delays))
#stationary

#2nd order difference
kpss.test(diff(diff(total_delays)))
#stationary
```

## BoxCox

```{r 3}
#all
l_flights<-BoxCox.lambda(total_flights)
l_delays<-BoxCox.lambda(total_delays)

#pre_covid
l_flights_pre_covid<-BoxCox.lambda(total_flights)
l_delays_pre_covid<-BoxCox.lambda(total_delays)
```

## Seasonal Naive

```{r 4}
#All
snaive_delays<-snaive(total_delays, h=12)
plot(snaive_delays)
accuracy(snaive_delays)
checkresiduals(snaive_delays)
#still autocorrelated

#Pre_covid
snaive_delays_pre_covid<-snaive(total_delays_pre_covid, h=12)
plot(snaive_delays_pre_covid)
accuracy(snaive_delays_pre_covid)
checkresiduals(snaive_delays_pre_covid)
#still autocorrelated
```

## Holt Winters

```{r 5}
#all
hw_delays <- hw(total_delays,seasonal = "multiplicative",h=12)
plot(hw_delays)
accuracy(hw_delays)
checkresiduals(hw_delays)
#still autocorrelated

#pre_covid
hw_delays_pre_covid <- hw(total_delays_pre_covid,seasonal = "multiplicative",h=12)
plot(hw_delays_pre_covid)
accuracy(hw_delays_pre_covid)
checkresiduals(hw_delays_pre_covid)
#still autocorrelated
```


## Holt Winters (Damped)

```{r 6}
#all
hw_delays_damped <- hw(total_delays,seasonal = "multiplicative",h=12,damped=TRUE)
plot(hw_delays_damped)
accuracy(hw_delays_damped)
checkresiduals(hw_delays_damped)
#still autocorrelated

#pre_covid
hw_delays_damped_pre_covid <- hw(total_delays_pre_covid,seasonal = "multiplicative",h=12,damped=TRUE)
plot(hw_delays_damped_pre_covid)
accuracy(hw_delays_damped_pre_covid)
checkresiduals(hw_delays_damped_pre_covid)
#still autocorrelated
```

## EACF

```{r 7}
#all
eacf(BoxCox(total_delays,l_delays))

#pre_covid
eacf(BoxCox(total_delays_pre_covid,l_delays_pre_covid))
```

## Auto Arima

```{r 8}
#A. all
aa_delays <- auto.arima(total_delays,l=l_delays)
aa_delays
accuracy(aa_delays)
checkresiduals(aa_delays)
#still autocorrelated
shapiro.test(aa_delays$residuals)
#not normally distributed 

#forecast
aa_delays_fcst<-forecast(aa_delays,h=12)
plot(aa_delays_fcst)

#B. pre_covid
aa_delays_pre_covid <- auto.arima(total_delays_pre_covid,l=l_delays_pre_covid)
aa_delays_pre_covid
accuracy(aa_delays_pre_covid)
checkresiduals(aa_delays_pre_covid)
#not autocorrelated
shapiro.test(aa_delays_pre_covid$residuals)
#normally distributed 

#forecast
aa_delays_fcst_pre_covid<-forecast(aa_delays_pre_covid,h=12)
plot(aa_delays_fcst_pre_covid)
```

## Auto Arima w/ XREF

```{r 9}
#A. all
#Uses naive forecast to predict flights into future
flights[,1]
aa_xref_delays <- auto.arima(total_delays,l=l_delays, xreg=total_flights)
aa_xref_delays
accuracy(aa_xref_delays)
checkresiduals(aa_xref_delays)
#autocorrelated
shapiro.test(aa_xref_delays$residuals)
#normally distributed 

#seasonal naive forecast for flights
flights_fcst <- snaive(total_flights, h=12)
plot(flights_fcst)

#forecast
aa_xref_delays<-forecast(aa_xref_delays,xreg=flights_fcst$mean,h=12)
plot(aa_xref_delays)

#B. pre_covid
#This one is slightly different than all b/c its trained on pre_covid data and then forecasted using all flights data during the covid era
aa_xref_delays_pre_covid <- auto.arima(total_delays_pre_covid,l=l_delays_pre_covid, xreg=total_flights_pre_covid)
aa_xref_delays_pre_covid
accuracy(aa_xref_delays_pre_covid)
checkresiduals(aa_xref_delays_pre_covid)
#autocorrelated
shapiro.test(aa_xref_delays_pre_covid$residuals)
#normally distributed

#limit flights to post 2019
post_covid_flights <- window(total_flights, start=2020)

#forecast
aa_xref_delays_pre_covid<-forecast(aa_xref_delays_pre_covid,xreg=matrix(post_covid_flights),h=29)
plot(aa_xref_delays_pre_covid)
```

## VAR

```{r 10}
#A. all
var_delays <- VAR(cbind(total_delays, total_flights), p=10, type ='both', season=12)
summary(var_delays)

#forecast
var_delays_fcst<-forecast(var_delays, h=12)
plot(var_delays_fcst)

#acf
acf(residuals(var_delays))

#serial test
serial.test(var_delays, lags.pt=10,type='PT.asymptotic')

#B. pre_covid
var_delays_pre_covid <- VAR(cbind(total_delays_pre_covid, total_flights_pre_covid), p=10, type ='both', season=12)
summary(var_delays_pre_covid)

#forecast
var_delays_pre_covid_fcst<-forecast(var_delays_pre_covid, h=12)
plot(var_delays_pre_covid_fcst)

#acf
acf(residuals(var_delays_pre_covid))

#serial test
serial.test(var_delays_pre_covid, lags.pt=10,type='PT.asymptotic')
```