---
title: "Group Project EDA"
author: "Arjun Venkatesh"
date: "2022-08-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(fpp)
library(tseries)
library(ggplot2)
library(forecast)
library(TSstudio)
library(MLmetrics)
library(vars)
library(dplyr)
```

## Importing Data

Import raw data. Selecting data only for O'Hare with all providers. Data is by month by provider, so need to aggregate by month.

```{r cars}
data <- read.csv('Airline_Delay_Cause.csv')
data[is.na(data)] <- 0

data$date <- as.Date(paste(data$year,'-',data$month,'-','01', sep = ''))


flights <- data %>% group_by(date) %>%
  summarise(flights = sum(arr_flights), delays = sum(arr_del15), carrier = sum(carrier_ct),
            weather = sum(weather_ct), nas = sum(nas_ct), security = sum(security_ct), 
            late_aircraft = sum(late_aircraft_ct), late_aircraft = sum(late_aircraft_ct),
            cancellation = sum(arr_cancelled), diversions = sum(arr_diverted))

flights = subset(flights, select = -c(date))

flights_ts <- ts(flights, start = c(2003,6), frequency = 12)
total_flights <- flights_ts[,1]
total_delays <- flights_ts[,2]
```

## EDA

Plot our main time series

```{r pressure, echo=FALSE}
tsdisplay(total_flights)
tsdisplay(total_delays)
```


