---
title: "Simple Forecasts"
author: "Arjun Venkatesh"
date: "2022-08-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(fpp)
library(tseries)
library(ggplot2)
library(forecast)
library(TSstudio)
library(MLmetrics)
library(vars)
library(dplyr)
library(TSA)
```

## Importing Data


```{r cars}
data <- read.csv('Airline_Delay_Cause.csv')
data[is.na(data)] <- 0

data$date <- as.Date(paste(data$year,'-',data$month,'-','01', sep = ''))


flights <- data %>% group_by(date) %>%
  summarise(flights = sum(arr_flights), delays = sum(arr_del15), carrier = sum(carrier_ct),
            weather = sum(weather_ct), nas = sum(nas_ct), security = sum(security_ct), 
            late_aircraft = sum(late_aircraft_ct), late_aircraft = sum(late_aircraft_ct),
            cancellation = sum(arr_cancelled), diversions = sum(arr_diverted))

flights = subset(flights, select = -c(date))

flights_ts <- ts(flights, start = c(2003,6), frequency = 12)
total_flights <- flights_ts[,1]
total_delays <- flights_ts[,2]

plot(total_delays)

train <- ts(total_delays[1:187], start = c(2003,6), frequency = 12)
test <- ts(total_delays[188:200], start = c(2019,1), frequency = 12)

train_covid <- ts(total_delays[1:216], start = c(2003,6), frequency = 12)
test_covid <- ts(total_delays[217:228], start = c(2021,6), frequency = 12)

total_flights_pre_covid <- window(total_flights, end=2019.99)
total_delays_pre_covid <- window(total_delays, end=2019.99)
```

## Exponential Smoothing


```{r}
snaive_delays<- snaive(train, h=12)
plot(snaive_delays)
accuracy(snaive_delays, test)
ts.plot(cbind(train, test, snaive_delays$mean), lty=1:3, col=1:3, main = 'naive_seasonal')
legend('topright', legend = c('train','test','forecast'), col=1:3, lty=1:3 )

# snaive_delays_covid<-snaive(train_covid, h=12)
# plot(snaive_delays_covid)
# accuracy(snaive_delays_covid, test_covid)
# ts.plot(cbind(train_covid, test_covid, snaive_delays_covid$mean), lty=1:3)
```

## Arima

```{r}
fit1 <- auto.arima(train)
forecast1 <- forecast(fit1, h=12)
accuracy(forecast1, test)

plot(train, main='Actuals vs Fit')
points(fitted(fit1))
legend('topright', legend=c('actual','fitted'), lty=c(1,NA), pch = c(NA,1))

ts.plot(cbind(train, test, forecast1$mean), lty=1:3, col=1:3, main = 'ARIMA')
legend('topright', legend = c('train','test','forecast'), col=1:3, lty=1:3 )

fit2 <- auto.arima(train_covid)
forecast2 <- forecast(fit2, h=12)
accuracy(forecast2, test_covid)
ts.plot(cbind(train_covid, test_covid, forecast2$mean), lty=1:3)
```

## HW Method

```{r}
hw_delays <- hw(train,seasonal = "multiplicative",h=12)
plot(hw_delays)
accuracy(hw_delays, test)
ts.plot(cbind(train, test, hw_delays$mean), lty=1:3, col=1:3, main = "Holt's Winter")
legend('topright', legend = c('train','test','forecast'), col=1:3, lty=1:3 )

hw_delays_covid <- hw(train_covid,seasonal = "multiplicative",h=12)
plot(hw_delays_covid)
accuracy(hw_delays_covid, test_covid)
ts.plot(cbind(train_covid, test_covid, hw_delays_covid$mean), lty=1:3, col=1:3, main = 'hw')
legend('topright', legend = c('train','test','forecast'), col=1:3, lty=1:3 )
```

