---
title: "Final proyect"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "Simple Forecasts"
author: "Arjun Venkatesh"
date: "2022-08-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(fpp)
library(tseries)
library(ggplot2)
library(forecast)
library(TSstudio)
library(MLmetrics)
library(vars)
library(dplyr)
```
```{r}
#installing/loading the package:
if(!require(installr)) {
install.packages("installr"); require(installr)} #load / install+load installr

# using the package:
updateR() # this will start the updating process of your R installation.  It will check for newer versions, and if one is available, will guide you through the decisions you'd need to make.

## Importing Data

```
```{r cars}
data <- read.csv('Airline_Delay_Cause.csv')
data[is.na(data)] <- 0
data$date <- as.Date(paste(data$year,'-',data$month,'-','01', sep = ''))
flights <- data %>% group_by(date) %>%
  summarise(flights = sum(arr_flights), delays = sum(arr_del15), carrier = sum(carrier_ct),
            weather = sum(weather_ct), nas = sum(nas_ct), security = sum(security_ct), 
            late_aircraft = sum(late_aircraft_ct), late_aircraft = sum(late_aircraft_ct),
            cancellation = sum(arr_cancelled), diversions = sum(arr_diverted))
flights = subset(flights, select = -c(date))
flights_ts <- ts(flights, start = c(2003,6), frequency = 12)
total_flights <- flights_ts[,1]
total_delays <- flights_ts[,2]
plot(total_delays)
train <- ts(total_delays[1:187], start = c(2003,6), frequency = 12)
test <- ts(total_delays[188:200], start = c(2019,1), frequency = 12)
train_covid <- ts(total_delays[1:216], start = c(2003,6), frequency = 12)
test_covid <- ts(total_delays[217:228], start = c(2021,6), frequency = 12)
```
```{r}
TBATS_delays<- tbats(train)
plot(TBATS_delays)
ts.plot(cbind(train, test, TBATS_delays$mean), lty=1:3, col=1:3, main = 'TBATS')
legend('topright', legend = c('forecast'), col=1:3, lty=1:3 )

TBATS_delays


```
```{r}
tbats_delays<- tbats(train)
graphics.off()
win.graph(width=6, height=6, pointsize = 12)
autoplot(train)
fc_tbats<-forecast(TBATS_delays, 10*12)
win.graph(width=6, height=6, pointsize = 12)
autoplot(fc_tbats)
```
```{r}

fc_tbats<-forecast(tbats_delays, 5*12)
win.graph(width=6, height=6, pointsize = 12)
autoplot(fc_tbats)
fc_tbats
```
```{r}
TBATS_delays_COVID<- tbats(train_covid)
plot(TBATS_delays_COVID)
ts.plot(cbind(train_covid, test_covid, TBATS_delays_COVID$mean), lty=1:3, col=1:3, main = 'TBATS_COVID')
legend('topright', legend = c('train','test','forecast'), col=1:3, lty=1:3 )
TBATS_delays_COVID

```